In [1]:
#Cargar Librer√≠as
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import tensorflow as tf
import csv
%matplotlib inline
plt.rcParams['figure.figsize'] = (16, 9)
plt.style.use('fast')

from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense,Activation,Flatten
from sklearn.preprocessing import MinMaxScaler

In [3]:
#Cargar archivo .CSV con datos de delitos
#Si es necesario, a√∫n no se puede agregar m√°s variables

df = pd.read_csv("/Users/j.artigasalegra/Documents/tesis/Solicitud_Base_Datos/Base_Dato_Con_Coorednadas/DATOS GEOCODIFICADOS/DATOS_2014_RED.csv",  parse_dates=[0], index_col=0, names=['Delito', 'DiaSem', 'Mes', 'Hora', 'TipoV', 'Longitud', 'Latitud'])
df

        DiaSem  Mes  Hora  TipoV   Longitud    Latitud
Delito
1            3    1     1      2 -71.364279 -33.066009
2            3    1     4      1 -71.449283 -32.506328
3            3    1     5      1 -71.244152 -32.885247
4            3    1     5      4 -71.544414 -32.958467
5            3    1     6      1 -71.607311 -33.564088
6            3    1     8      1 -71.546929 -33.022157
7            3    1     9      3 -71.586060 -33.033630
8            3    1    11      5 -71.334306 -33.152032
9            3    1    13      1 -71.578250 -33.030275
10           3    1    22      2 -71.518253 -33.036472
11           4    1     0      1 -71.605127 -33.548376
12           5    1     2      1 -71.599784 -33.539632
13           5    1     4      1 -71.526981 -32.987312
14           5    1    10      2 -71.534616 -32.979286
15           5    1    10      1 -71.562452 -33.020004
16           5    1    18      1 -71.546292 -32.932899
17           5    1    18      1 -71.244152 -32.885247
18           5    1    21      1 -71.552552 -33.014981
19           5    1    22      1 -71.605043 -33.553662
20           5    1    22      6 -71.476582 -32.997061
21           6    1     4      1 -71.421913 -33.056774
22           6    1     4      1 -70.599434 -32.835096
23           6    1     4      1 -71.615098 -33.052516
24           6    1     6      1 -71.433584 -33.057880
25           6    1    14      5 -71.465636 -33.049843
26           6    1    23      1 -71.377244 -33.052524
27           7    1     0      1 -71.411866 -33.036271
28           7    1     0      1 -71.374004 -33.050424
29           7    1     1      1 -71.620490 -33.045658
30           7    1     2      1 -71.552114 -33.009839
...        ...  ...   ...    ...        ...        ...
2411         6   12     3      1 -71.694553 -33.398313
2412         6   12     3      3 -71.566390 -33.021091
2413         6   12     5      1 -71.598780 -33.057562
2414         7   12     0      5 -71.546654 -33.011586
2415         7   12     1      3 -71.540259 -32.941099
2416         7   12     3      2 -71.536246 -32.980661
2417         7   12    12      5 -71.429060 -33.047846
2418         7   12    17      1 -71.497532 -32.921101
2419         1   12     0      1 -71.610366 -33.554135
2420         1   12     1      6 -71.285034 -32.447878
2421         1   12     1      6 -71.477815 -32.716734
2422         1   12     8      1 -71.265770 -32.762170
2423         1   12    13      1 -71.475150 -32.995203
2424         1   12    17      2 -71.244514 -32.894574
2425         1   12    23      1 -71.542522 -32.963201
2426         2   12     1      2 -71.522930 -33.033290
2427         2   12     2      2 -71.539236 -32.977326
2428         2   12     6      1 -71.685680 -33.397688
2429         2   12     7      6 -71.618342 -33.605773
2430         2   12     7      2 -71.524877 -32.970988
2431         2   12     9      2 -71.515047 -33.036751
2432         2   12    12      1 -71.507735 -32.920623
2433         2   12    13      1 -71.444891 -33.057336
2434         2   12    17      1 -70.599434 -32.835096
2435         2   12    23      1 -70.594882 -32.834102
2436         2   12    23      1 -71.382730 -33.052345
2437         3   12     0      6 -71.234425 -32.860501
2438         3   12     2      1 -71.218872 -32.859547
2439         3   12    21      1 -71.607460 -33.594730
2440         3   12    22      1 -70.594983 -32.854415

[2440 rows x 6 columns]

In [4]:
df.describe()

,DiaSem,Mes,Hora,TipoV,Longitud,Latitud
count,2440.000000,2440.000000,2440.000000,2440.000000,2440.000000,2440.000000
mean,3.956557,6.169262,12.381148,2.061885,-71.612225,-32.998425
std,1.972483,3.378725,7.380413,1.604838,2.668238,0.460287
min,1.000000,1.000000,0.000000,1.000000,-109.436278,-33.921019
25%,2.000000,3.000000,6.000000,1.000000,-71.559836,-33.049016
50%,4.000000,6.000000,12.000000,1.000000,-71.518119,-33.028333
75%,6.000000,9.000000,20.000000,3.000000,-71.395749,-32.975777
max,7.000000,12.000000,23.000000,6.000000,-70.182509,-27.073739

In [5]:
# convertir series a aprendizaje supervizado
#Aprendizaje supervisado ser√° utilizando los 15 d√≠as previos para predecir el actual delito (latitud y longitud)

def series_to_supervised(data, n_in=1, n_out=2, dropnan=True):
    n_vars = 1 if type(data) is list else data.shape[1]
    df = pd.DataFrame(data)
    cols, names = list(), list()
    # input sequence (t-n, ... t-1)
    for i in range(n_in, 0, -1):
        cols.append(df.shift(i))
        names += [('var%d(t-%d)' % (j+1, i)) for j in range(n_vars)]
    # forecast sequence (t, t+1, ... t+n)
    for i in range(0, n_out):
        cols.append(df.shift(-i))
        if i == 0:
            names += [('var%d(t)' % (j+1)) for j in range(n_vars)]
        else:
            names += [('var%d(t+%d)' % (j+1, i)) for j in range(n_vars)]
    # put it all together
    agg = pd.concat(cols, axis=1)
    agg.columns = names
    # drop rows with NaN values
    if dropnan:
        agg.dropna(inplace=True)
    return agg

In [ ]:
#Normalizar datos de variable "Dia de la semana"
PASOS=15

# load dataset
values = df['DiaSem'].values

# ensure all data is float
values = values.astype('float32')

# normalize features
scaler = MinMaxScaler(feature_range=(0, 1))
values=values.reshape(-1, 1) # esto lo hacemos porque tenemos 1 sola dimension
DiaSemN = scaler.fit_transform(values)

df['DiaSemN'] = DiaSemN
scaledMerge=df.drop(columns=['DiaSem'])
print(scaledMerge)

# frame as supervised learning
reframed = series_to_supervised(scaledMerge, PASOS, 1)
reframed.head()

In [ ]:
#Normalizar datos de variable "Mes del delito"
PASOS=15

# load dataset
values2 = df['Mes'].values

# ensure all data is float
values2 = values2.astype('float32')

# normalize features
scaler = MinMaxScaler(feature_range=(0, 1))
values2=values2.reshape(-1, 1) # esto lo hacemos porque tenemos 1 sola dimension
MesN = scaler.fit_transform(values2)

df['MesN'] = MesN
scaledMerge2=df.drop(columns=['DiaSem','Mes'])
print(scaledMerge2)

# frame as supervised learning
reframed = series_to_supervised(scaledMerge2, PASOS, 1)
reframed.head()

In [ ]:
#Normalizar datos de variable "Hora del delito"
PASOS=15

# load dataset
values3 = df['Hora'].values

# ensure all data is float
values3 = values3.astype('float32')

# normalize features
scaler = MinMaxScaler(feature_range=(0, 1))
values3=values3.reshape(-1, 1) # esto lo hacemos porque tenemos 1 sola dimension
HoraN = scaler.fit_transform(values3)

df['HoraN'] = HoraN
scaledMerge3=df.drop(columns=['DiaSem','Mes', 'Hora'])
print(scaledMerge3)

# frame as supervised learning
reframed = series_to_supervised(scaledMerge3, PASOS, 1)
reframed.head()

In [ ]:
#Normalizar datos de variable "Tipo vehiculo robado"
PASOS=15

# load dataset
values4 = df['TipoV'].values

# ensure all data is float
values4 = values4.astype('float32')

# normalize features
scaler = MinMaxScaler(feature_range=(0, 1))
values4=values4.reshape(-1, 1) # esto lo hacemos porque tenemos 1 sola dimension
TipoVN = scaler.fit_transform(values4)

df['TipoVN'] = TipoVN
scaledMerge4=df.drop(columns=['DiaSem','Mes', 'Hora','TipoV'])
print(scaledMerge4)

# frame as supervised learning
reframed = series_to_supervised(scaledMerge4, PASOS, 1)
reframed.head()

In [ ]:
#Normalizar datos de variable "Longitud del delito"
PASOS=15

# load dataset
values5 = df['Longitud'].values

# ensure all data is float
values5 = values5.astype('float32')

# normalize features
scaler = MinMaxScaler(feature_range=(0, 1))
values5=values5.reshape(-1, 1) # esto lo hacemos porque tenemos 1 sola dimension
LongitudN = scaler.fit_transform(values5)

df['LongitudN'] = LongitudN
scaledMerge5=df.drop(columns=['DiaSem','Mes','Hora', 'TipoV','Longitud'])
print(scaledMerge5)

# frame as supervised learning
reframed = series_to_supervised(scaledMerge5, PASOS, 1)
reframed.head()

In [ ]:
#Normalizar datos de variable "Latitud del delito"
PASOS=15

# load dataset
values6 = df['Latitud'].values

# ensure all data is float
values6 = values6.astype('float32')

# normalize features
scaler = MinMaxScaler(feature_range=(0, 1))
values6=values6.reshape(-1, 1) # esto lo hacemos porque tenemos 1 sola dimension
LatitudN = scaler.fit_transform(values6)

df['LatitudN'] = LatitudN
scaledMerge6=df.drop(columns=['DiaSem','Mes','Hora', 'TipoV','Longitud', 'Latitud'])
print(scaledMerge6)

# frame as supervised learning
reframed = series_to_supervised(scaledMerge6, PASOS, 1)
reframed.head()

In [ ]:
#Se elimina las otras variables en perido t para solo tener como salida Longitud y Latitud

newReframed=reframed.drop(columns=['var1(t)','var2(t)','var3(t)','var4(t)'])
print(newReframed.shape)
newReframed.head()

In [ ]:
#Separar datos como datos de entrenamiento y datos de prueba 
#Separa los datos en 70% (1700) train y 30% (725) validaci√≥n

values = newReframed.values
train = values[1:1701, :]
test = values[1701:2426, :]

# split into input and outputs

x_train, y_train = train[:, 1:91], train[:, [90,91]]
x_val, y_val = test[:, 1:91], test[:, [90,91]]

# reshape input to be 3D [samples, timesteps, features]
#x_train = x_train.reshape((x_train.shape[0], 1,x_train.shape[1]))
#x_val = x_val.reshape((x_val.shape[0], 1, x_val.shape[1]))
print(x_train.shape, y_train.shape, x_val.shape, y_val.shape)

In [ ]:
#Se define la red neuronal, cuando tenga la red lista, probare con distintas funciones de activaci√≥n o nodos

def crear_modeloFF():
    model = Sequential() 
    model.add(Dense(90, input_dim=(90), kernel_initializer='normal',activation='tanh'))
    model.add(Dense(2, kernel_initializer='normal', activation='tanh'))
    model.compile(loss='mean_absolute_error',optimizer='Adam',metrics=["mse"])
    model.summary()
    return model

In [ ]:
#Despues de tener lista la red, variare EPOCHS para ver como mejoran los resultados
EPOCHS=40

model = crear_modeloFF()

history=model.fit(x_train,y_train,epochs=EPOCHS,validation_data=(x_val,y_val),batch_size=1)

In [ ]:
#Gr√°fico comparativo de los resultados de la red vs los valores de prueba

results=model.predict(x_val)

#Entrega los valores 1 por 1 quitando "Len()"
print(len(results[:,0])) #Columna 1 "Longitud"
print(len(results[:,1])) #Columna 2 "Latitud"

#Permite visualizar que tanto se acerca la predicci√≥n con los valores de validaci√≥n
plt.scatter(range(len(y_val[:, 0])),y_val[:, 0],c='g')
plt.scatter(range(len(results[:, 0])),results[:, 0],c='r')
plt.title('Validate_Longitud')
plt.show()

plt.scatter(range(len(y_val[:, 1])),y_val[:, 1],c='g')
plt.scatter(range(len(results[:, 1])),results[:, 1],c='r')
plt.title('Validate_Latitud')
plt.show()

In [ ]:
#Permite graficar la p√©rdida LOSS tanto del conjunto de ENTENAMIENTO(azul)  como de VALIDACION(naranja)

plt.ylim(0.005, 0.1)
plt.plot(history.history['loss'])
plt.title('loss')
plt.plot(history.history['val_loss'])
plt.title('validate loss')
plt.show()

In [ ]:
plt.ylim(0.001, 0.13)
plt.title('Accuracy')
plt.plot(history.history['mse'])
plt.show()

In [ ]:
#Compara resultados con la predicci√≥n y obtenemos diferencia que hay entre el dato real y el predicho

compara_Latitud = pd.DataFrame(np.array([y_val[:, 1], [x[1] for x in results]])).transpose()
compara_Latitud

inverted_Latitud = scaler.inverse_transform(compara_Latitud.values)

compara_Lat = pd.DataFrame(inverted_Latitud)
compara_Lat.columns = ['real', 'prediccion']
compara_Lat['diferencia'] = compara_Lat['real'] - compara_Lat['prediccion']
compara_Lat.head(4)

In [ ]:
#Compara resultados con la predicci√≥n y obtenemos diferencia que hay entre el dato real y el predicho
#Al invertir los datos a origianles, hay problemas con "Longitud", ya que devuelve datos nada que ver.
#Como se logra ver, al invertir los datos de "LongitudN" son numeros cercanaos al -27 y deber√≠a rondar el -72

compara_Longitud = pd.DataFrame(np.array([y_val[:, 0], [x[0] for x in results]])).transpose()
compara_Longitud

inverted_Longitud = scaler.inverse_transform(compara_Longitud.values)

compara_Lon = pd.DataFrame(inverted_Longitud)
compara_Lon.columns = ['real', 'prediccion']
compara_Lon['diferencia'] = compara_Lon['real'] - compara_Lon['prediccion']
compara_Lon.head(4)

In [ ]:
#Gr√°fico de los resultados de la predicci√≥n versus los datos reales
#de variable "Longitud del delito"

compara_Lon['real'].plot() #Color azul
compara_Lon['prediccion'].plot() #Color naranjo

In [ ]:
#Gr√°fico de los resultados de la predicci√≥n versus los datos reales
#de variable "Latitud del delito"


compara_Lat['real'].plot() #Color azul
compara_Lat['prediccion'].plot() #Color naranjo